#!/usr/bin/env bash
# reproduce_figures.sh — regenerate all MAIN + named-supplementary paper figures
# for the jaxon manuscript from PROCESSED data (Path A in REPRODUCE.md).
#
# This is fast (~5-15 min), CPU-only, and needs NO GPU and NO pyfibers/NEURON
# compile: every figure script here only reads JSON from outputs/ and renders.
#
# Prerequisites:
#   * conda env `jaxon` active   (conda activate jaxon)
#   * run from the repo root
#   * outputs/ populated (from the repo or the Zenodo bundle); in particular
#     outputs/duke_sweeps_fixed/ must exist (the corrected cohort sweep)
#
# It does NOT run the slow upstream producers (validation / scaling / phenomena
# / duke FEM sweep) — see REPRODUCE.md §3 (Path B) for those.
#
# Deliberately NOT emitted here (see REPRODUCE.md caveats):
#   * figS_density        -> no in-repo scripted regenerator (committed asset)
#   * cohort penalty table -> analyze_sparse_sampling.py (honors DUKE_SWEEP_ROOT); run separately

set -euo pipefail

# --- locate repo root (dir containing this script) and cd into it ------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

# --- the corrected cohort sweep tree, read by the duke figure scripts --------
export DUKE_SWEEP_ROOT="${DUKE_SWEEP_ROOT:-outputs/duke_sweeps_fixed}"

echo "=============================================================="
echo " jaxon figure reproduction (Path A — from processed data)"
echo "   repo root       : ${SCRIPT_DIR}"
echo "   DUKE_SWEEP_ROOT : ${DUKE_SWEEP_ROOT}"
echo "   python          : $(command -v python)"
echo "=============================================================="

if [ ! -d "${DUKE_SWEEP_ROOT}" ]; then
  echo "ERROR: ${DUKE_SWEEP_ROOT} not found — the duke figures need the corrected" >&2
  echo "       cohort sweep. Populate outputs/ (repo or Zenodo bundle) first." >&2
  exit 1
fi

run() {
  # run <human label> <python -m module ...>
  local label="$1"; shift
  echo
  echo "-------------------------------------------------------------"
  echo ">>> ${label}"
  echo ">>> \$ $*"
  echo "-------------------------------------------------------------"
  "$@"
}

# --- MAIN figures ------------------------------------------------------------
run "Fig 1 — validation (thresholds, CV, scaling)" \
    python -m experiments_v2.figures_validation_main

run "Fig 2 — propagation phenomena (4 models x 3 columns)" \
    python -m experiments_v2.figures_phenomena_main

run "Fig 3 — Duke cohort (selectivity, deployment penalty, recruitment)" \
    python -m experiments_v2.figures_duke_main

# --- NAMED supplementary figures ---------------------------------------------
run "figS_khz_block — kHz frequency block, all 4 models" \
    python -m experiments_v2.figures_phenomena_supp_khz

run "figS_optimizer_validation — gradient correctness + convergence" \
    python -m experiments_v2.fig_optimizer_validation

# --- PER-SPECIMEN supplementary figure sets (29 nerves each) -----------------
run "figA_* — per-specimen anatomy / FEM pages (x29)" \
    python -m experiments_v2.figures_supp_anatomy

run "figS_* — per-specimen selectivity / activation pages (x29)" \
    python -m experiments_v2.figures_supp_activation

echo
echo "=============================================================="
echo " DONE. Figures written under:"
echo "   manuscript/figures/main/   (fig1_validation, fig2_phenomena, fig3_duke)"
echo "   manuscript/figures/supp/   (figS_khz_block, figS_optimizer_validation,"
echo "                               figA_<nerve>, figS_<nerve>)"
echo
echo " NOT regenerated by this driver (see REPRODUCE.md caveats):"
echo "   figS_density              (no in-repo scripted regenerator)"
echo "   cohort penalty table      (run analyze_sparse_sampling.py separately;"
echo "                              honors DUKE_SWEEP_ROOT)"
echo "=============================================================="
